export interface KeywordDefinition {
  keyword: string
  type: 'ability' | 'action' | 'mechanic'
  tier: 'evergreen' | 'returning' | 'retired'
  definition: string
  reminder?: string
  example?: string
  introduced?: string
  scryfallQuery?: string
}

export const KEYWORDS: KeywordDefinition[] = [
  // ── Evergreen Abilities ─────────────────────────────────────────────
  {
    keyword: 'Flying',
    type: 'ability',
    tier: 'evergreen',
    definition: 'This creature can only be blocked by creatures with flying or reach.',
    reminder: "This creature can't be blocked except by creatures with flying and/or reach.",
    example: 'Serra Angel',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:flying',
  },
  {
    keyword: 'First Strike',
    type: 'ability',
    tier: 'evergreen',
    definition: 'This creature deals combat damage before creatures without first strike.',
    reminder: "This creature deals combat damage before creatures without first strike.",
    example: 'Benalish Marshal',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:"first strike"',
  },
  {
    keyword: 'Double Strike',
    type: 'ability',
    tier: 'evergreen',
    definition: 'This creature deals both first-strike and regular combat damage.',
    reminder: 'This creature deals both first-strike and regular combat damage.',
    example: 'Mirran Crusader',
    introduced: 'Legions',
    scryfallQuery: 'o:"double strike"',
  },
  {
    keyword: 'Deathtouch',
    type: 'ability',
    tier: 'evergreen',
    definition: 'Any amount of damage this deals to a creature is enough to destroy it.',
    reminder: 'Any amount of damage this deals to a creature is enough to destroy it.',
    example: 'Vampire Nighthawk',
    introduced: 'Future Sight',
    scryfallQuery: 'o:deathtouch',
  },
  {
    keyword: 'Defender',
    type: 'ability',
    tier: 'evergreen',
    definition: "This creature can't attack.",
    reminder: "This creature can't attack.",
    example: 'Wall of Omens',
    introduced: 'Champions of Kamigawa',
    scryfallQuery: 'o:defender',
  },
  {
    keyword: 'Haste',
    type: 'ability',
    tier: 'evergreen',
    definition: 'This creature can attack and tap the turn it comes under your control.',
    reminder: 'This creature can attack and tap as soon as it comes under your control.',
    example: 'Goblin Guide',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:haste',
  },
  {
    keyword: 'Hexproof',
    type: 'ability',
    tier: 'evergreen',
    definition: "This permanent can't be the target of spells or abilities your opponents control.",
    reminder: "This creature can't be the target of spells or abilities your opponents control.",
    example: 'Invisible Stalker',
    introduced: 'Magic 2012',
    scryfallQuery: 'o:hexproof',
  },
  {
    keyword: 'Indestructible',
    type: 'ability',
    tier: 'evergreen',
    definition: 'Effects that say "destroy" don\'t destroy this permanent. A creature with indestructible can\'t be destroyed by damage.',
    reminder: 'Damage and effects that say "destroy" don\'t destroy this permanent.',
    example: 'Darksteel Colossus',
    introduced: 'Darksteel',
    scryfallQuery: 'o:indestructible',
  },
  {
    keyword: 'Lifelink',
    type: 'ability',
    tier: 'evergreen',
    definition: 'Damage dealt by this permanent also causes you to gain that much life.',
    reminder: 'Damage dealt by this creature also causes you to gain that much life.',
    example: 'Vampire Nighthawk',
    introduced: 'Future Sight',
    scryfallQuery: 'o:lifelink',
  },
  {
    keyword: 'Menace',
    type: 'ability',
    tier: 'evergreen',
    definition: "This creature can't be blocked except by two or more creatures.",
    reminder: "This creature can't be blocked except by two or more creatures.",
    example: 'Goblin Heelcutter',
    introduced: 'Magic Origins',
    scryfallQuery: 'o:menace',
  },
  {
    keyword: 'Reach',
    type: 'ability',
    tier: 'evergreen',
    definition: 'This creature can block creatures with flying.',
    reminder: 'This creature can block creatures with flying.',
    example: 'Giant Spider',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:reach',
  },
  {
    keyword: 'Trample',
    type: 'ability',
    tier: 'evergreen',
    definition: "This creature can deal excess combat damage to the player or planeswalker it's attacking.",
    reminder: "This creature can deal excess combat damage to the player or planeswalker it's attacking.",
    example: 'Colossal Dreadmaw',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:trample',
  },
  {
    keyword: 'Vigilance',
    type: 'ability',
    tier: 'evergreen',
    definition: "Attacking doesn't cause this creature to tap.",
    reminder: "Attacking doesn't cause this creature to tap.",
    example: 'Serra Angel',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:vigilance',
  },
  {
    keyword: 'Ward',
    type: 'ability',
    tier: 'evergreen',
    definition: "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays the ward cost.",
    reminder: "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays [cost].",
    example: 'Wandering Emperor',
    introduced: 'Strixhaven',
    scryfallQuery: 'o:ward',
  },
  {
    keyword: 'Flash',
    type: 'ability',
    tier: 'evergreen',
    definition: 'You may cast this spell any time you could cast an instant.',
    reminder: 'You may cast this spell any time you could cast an instant.',
    example: 'Snapcaster Mage',
    introduced: 'Mirage',
    scryfallQuery: 'o:flash',
  },

  // ── Keyword Actions (Returning) ─────────────────────────────────────
  {
    keyword: 'Activate',
    type: 'action',
    tier: 'returning',
    definition: 'To put an activated ability on the stack and pay its costs.',
    example: 'Prodigal Pyromancer',
  },
  {
    keyword: 'Attach',
    type: 'action',
    tier: 'returning',
    definition: 'To move an Equipment or Aura onto a creature or other permanent.',
    example: 'Bonesplitter',
  },
  {
    keyword: 'Cast',
    type: 'action',
    tier: 'returning',
    definition: 'To take a spell from your hand (or another zone) and put it on the stack, paying its costs.',
    example: 'Lightning Bolt',
  },
  {
    keyword: 'Counter',
    type: 'action',
    tier: 'returning',
    definition: "To cancel a spell or ability so it doesn't resolve and none of its effects occur.",
    example: 'Counterspell',
  },
  {
    keyword: 'Destroy',
    type: 'action',
    tier: 'returning',
    definition: "To move a permanent from the battlefield to its owner's graveyard. Indestructible permanents can't be destroyed.",
    example: 'Murder',
  },
  {
    keyword: 'Discard',
    type: 'action',
    tier: 'returning',
    definition: "To move a card from your hand to your graveyard.",
    example: 'Mind Rot',
  },
  {
    keyword: 'Exile',
    type: 'action',
    tier: 'returning',
    definition: 'To put an object into the exile zone. Exiled cards are removed from the game (unless an effect returns them).',
    example: 'Path to Exile',
  },
  {
    keyword: 'Sacrifice',
    type: 'action',
    tier: 'returning',
    definition: "To move a permanent you control to its owner's graveyard. You can't sacrifice permanents you don't control.",
    example: 'Diabolic Intent',
  },
  {
    keyword: 'Scry',
    type: 'action',
    tier: 'returning',
    definition: 'Look at the top N cards of your library, then put any number on the bottom in any order and the rest on top in any order.',
    reminder: 'Look at the top N cards of your library, then put any number of them on the bottom and the rest on top in any order.',
    example: 'Opt',
    scryfallQuery: 'o:scry',
  },
  {
    keyword: 'Search',
    type: 'action',
    tier: 'returning',
    definition: 'To look at all cards in a stated zone and find cards that match the given criteria.',
    example: 'Rampant Growth',
  },
  {
    keyword: 'Shuffle',
    type: 'action',
    tier: 'returning',
    definition: 'To randomize the order of cards in your library.',
    example: 'Evolving Wilds',
  },
  {
    keyword: 'Tap',
    type: 'action',
    tier: 'returning',
    definition: 'To turn a permanent sideways, indicating it has been used. Tapped creatures cannot block.',
    example: 'Llanowar Elves',
  },
  {
    keyword: 'Untap',
    type: 'action',
    tier: 'returning',
    definition: 'To return a tapped permanent to its upright position, readying it for use again.',
    example: 'Seedborn Muse',
  },

  // ── Returning Mechanics ─────────────────────────────────────────────
  {
    keyword: 'Flashback',
    type: 'mechanic',
    tier: 'returning',
    definition: 'You may cast this card from your graveyard for its flashback cost, then exile it.',
    reminder: 'You may cast this card from your graveyard for its flashback cost. Then exile it.',
    example: 'Think Twice',
    introduced: 'Odyssey',
    scryfallQuery: 'o:flashback',
  },
  {
    keyword: 'Kicker',
    type: 'mechanic',
    tier: 'returning',
    definition: 'You may pay an additional cost as you cast this spell. If you do, additional effects occur.',
    reminder: 'You may pay an additional [cost] as you cast this spell.',
    example: 'Hallar, the Firefletcher',
    introduced: 'Invasion',
    scryfallQuery: 'o:kicker',
  },
  {
    keyword: 'Equip',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Pay the equip cost and attach this Equipment to target creature you control. Equip only as a sorcery.',
    reminder: '[Cost]: Attach to target creature you control. Equip only as a sorcery.',
    example: 'Sword of Fire and Ice',
    introduced: 'Mirrodin',
    scryfallQuery: 'o:equip',
  },
  {
    keyword: 'Prowess',
    type: 'ability',
    tier: 'returning',
    definition: 'Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.',
    reminder: 'Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.',
    example: 'Monastery Swiftspear',
    introduced: 'Khans of Tarkir',
    scryfallQuery: 'o:prowess',
  },
  {
    keyword: 'Convoke',
    type: 'mechanic',
    tier: 'returning',
    definition: "Your creatures can help cast this spell. Each creature you tap while casting this spell pays for 1 or one mana of that creature's color.",
    reminder: "Your creatures can help cast this spell. Each creature you tap while casting this spell pays for 1 or one mana of that creature's color.",
    example: 'Chord of Calling',
    introduced: 'Ravnica',
    scryfallQuery: 'o:convoke',
  },
  {
    keyword: 'Cascade',
    type: 'mechanic',
    tier: 'returning',
    definition: 'When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.',
    reminder: 'When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom of your library in a random order.',
    example: 'Bloodbraid Elf',
    introduced: 'Alara Reborn',
    scryfallQuery: 'o:cascade',
  },
  {
    keyword: 'Delve',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Each card you exile from your graveyard while casting this spell pays for 1.',
    reminder: 'Each card you exile from your graveyard while casting this spell pays for 1.',
    example: 'Treasure Cruise',
    introduced: 'Future Sight',
    scryfallQuery: 'o:delve',
  },
  {
    keyword: 'Cycling',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Pay the cycling cost and discard this card: Draw a card.',
    reminder: '[Cost], Discard this card: Draw a card.',
    example: 'Decree of Justice',
    introduced: "Urza's Saga",
    scryfallQuery: 'o:cycling',
  },
  {
    keyword: 'Landfall',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Whenever a land enters the battlefield under your control, this ability triggers.',
    example: 'Lotus Cobra',
    introduced: 'Zendikar',
    scryfallQuery: 'o:landfall',
  },
  {
    keyword: 'Annihilator',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Whenever this creature attacks, defending player sacrifices N permanents.',
    reminder: 'Whenever this creature attacks, defending player sacrifices N permanents.',
    example: 'Ulamog, the Infinite Gyre',
    introduced: 'Rise of the Eldrazi',
    scryfallQuery: 'o:annihilator',
  },
  {
    keyword: 'Affinity',
    type: 'mechanic',
    tier: 'returning',
    definition: 'This spell costs 1 less to cast for each [object] you control.',
    reminder: 'This spell costs 1 less to cast for each [object] you control.',
    example: 'Thoughtcast',
    introduced: 'Mirrodin',
    scryfallQuery: 'o:affinity',
  },
  {
    keyword: 'Modular',
    type: 'mechanic',
    tier: 'returning',
    definition: 'This creature enters the battlefield with N +1/+1 counters on it. When it dies, you may put its +1/+1 counters on target artifact creature.',
    reminder: 'This creature enters the battlefield with N +1/+1 counters on it. When it dies, you may put its +1/+1 counters on target artifact creature.',
    example: 'Arcbound Ravager',
    introduced: 'Darksteel',
    scryfallQuery: 'o:modular',
  },
  {
    keyword: 'Protection',
    type: 'ability',
    tier: 'returning',
    definition: "This permanent can't be blocked, targeted, dealt damage, enchanted, or equipped by anything with the stated quality.",
    reminder: "This creature can't be blocked, targeted, dealt damage, or enchanted by anything [quality].",
    example: 'White Knight',
    introduced: 'Limited Edition Alpha',
    scryfallQuery: 'o:protection',
  },

  // ── Additional Returning — Graveyard Abilities ───────────────────────
  {
    keyword: 'Dredge',
    type: 'mechanic',
    tier: 'returning',
    definition: 'If you would draw a card, instead you may mill N cards. If you do, return this card from your graveyard to your hand.',
    reminder: 'If you would draw a card, you may instead put N cards from the top of your library into your graveyard. If you do, return this card from your graveyard to your hand.',
    example: 'Golgari Grave-Troll',
    introduced: 'Ravnica: City of Guilds',
    scryfallQuery: 'o:dredge',
  },
  {
    keyword: 'Madness',
    type: 'mechanic',
    tier: 'returning',
    definition: 'If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it in your graveyard.',
    reminder: 'If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.',
    example: 'Fiery Temper',
    introduced: 'Odyssey',
    scryfallQuery: 'o:madness',
  },
  {
    keyword: 'Escape',
    type: 'mechanic',
    tier: 'returning',
    definition: 'You may cast this card from your graveyard for its escape cost by exiling the required number of other cards from your graveyard.',
    reminder: 'You may cast this card from your graveyard for its escape cost.',
    example: "Uro, Titan of Nature's Wrath",
    introduced: 'Theros Beyond Death',
    scryfallQuery: 'o:escape',
  },
  {
    keyword: 'Embalm',
    type: 'mechanic',
    tier: 'returning',
    definition: "Exile this card from your graveyard: Create a token that's a copy of it, except it's a white Zombie in addition to its other types. Embalm only as a sorcery.",
    reminder: "[Cost], Exile this card from your graveyard: Create a token that's a copy of it, except it's a white Zombie in addition to its other colors and types. Embalm only as a sorcery.",
    example: 'Vizier of Many Faces',
    introduced: 'Amonkhet',
    scryfallQuery: 'o:embalm',
  },
  {
    keyword: 'Eternalize',
    type: 'mechanic',
    tier: 'returning',
    definition: "Exile this card from your graveyard: Create a token that's a copy of it, except it's 4/4, black, and a Zombie in addition to its other types. Eternalize only as a sorcery.",
    reminder: "[Cost], Exile this card from your graveyard: Create a token that's a copy of it, except it's 4/4 black Zombie in addition to its other types and colors. Eternalize only as a sorcery.",
    example: 'Champion of Wits',
    introduced: 'Hour of Devastation',
    scryfallQuery: 'o:eternalize',
  },
  {
    keyword: 'Disturb',
    type: 'mechanic',
    tier: 'returning',
    definition: 'You may cast this card from your graveyard transformed for its disturb cost.',
    reminder: 'You may cast this card from your graveyard transformed for its disturb cost.',
    example: 'Lunarch Veteran',
    introduced: 'Innistrad: Midnight Hunt',
    scryfallQuery: 'o:disturb',
  },
  {
    keyword: 'Unearth',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth only as a sorcery.',
    reminder: 'Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth only as a sorcery.',
    example: 'Viscera Dragger',
    introduced: 'Shards of Alara',
    scryfallQuery: 'o:unearth',
  },

  // ── Additional Returning — Counter/Resource Abilities ────────────────
  {
    keyword: 'Persist',
    type: 'ability',
    tier: 'returning',
    definition: "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner's control with a -1/-1 counter on it.",
    reminder: "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner's control with a -1/-1 counter on it.",
    example: 'Kitchen Finks',
    introduced: 'Shadowmoor',
    scryfallQuery: 'o:persist',
  },
  {
    keyword: 'Undying',
    type: 'ability',
    tier: 'returning',
    definition: "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner's control with a +1/+1 counter on it.",
    reminder: "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner's control with a +1/+1 counter on it.",
    example: "Geralf's Messenger",
    introduced: 'Dark Ascension',
    scryfallQuery: 'o:undying',
  },
  {
    keyword: 'Wither',
    type: 'ability',
    tier: 'returning',
    definition: 'This creature deals damage to creatures in the form of -1/-1 counters.',
    reminder: 'This creature deals damage to creatures in the form of -1/-1 counters.',
    example: 'Boggart Ram-Gang',
    introduced: 'Shadowmoor',
    scryfallQuery: 'o:wither',
  },
  {
    keyword: 'Infect',
    type: 'ability',
    tier: 'returning',
    definition: 'This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters. A player with 10 or more poison counters loses the game.',
    reminder: 'This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.',
    example: 'Glistener Elf',
    introduced: 'Scars of Mirrodin',
    scryfallQuery: 'o:infect',
  },
  {
    keyword: 'Toxic',
    type: 'ability',
    tier: 'returning',
    definition: 'Whenever this creature deals combat damage to a player, that player gets N poison counters.',
    reminder: 'Whenever this creature deals combat damage to a player, that player gets N poison counter(s).',
    example: 'Venomous Bruiser',
    introduced: 'Phyrexia: All Will Be One',
    scryfallQuery: 'o:toxic',
  },
  {
    keyword: 'Rad',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Players accumulate rad counters. At the beginning of each end step, each player mills cards equal to their rad counters and loses life equal to the number of nonland cards milled this way.',
    example: 'Rads of Doom',
    introduced: 'Commander: Fallout',
    scryfallQuery: 'o:rad',
  },
  {
    keyword: 'Energy',
    type: 'mechanic',
    tier: 'returning',
    definition: 'A resource counter represented by ⚡. Cards give you energy counters or let you pay energy counters for effects. Energy does not reset between turns.',
    reminder: '(Each ⚡ is an energy counter.)',
    example: 'Aetherworks Marvel',
    introduced: 'Kaladesh',
    scryfallQuery: 'o:energy',
  },
  {
    keyword: 'Experience',
    type: 'mechanic',
    tier: 'returning',
    definition: 'A counter placed on you as a player (not on a permanent). Certain legendary commanders get stronger as you accumulate more experience counters.',
    example: 'Meren of Clan Nel Toth',
    introduced: 'Commander 2015',
    scryfallQuery: 'o:"experience counter"',
  },
  {
    keyword: 'Adapt',
    type: 'mechanic',
    tier: 'returning',
    definition: 'If this creature has no +1/+1 counters on it, put N +1/+1 counters on it.',
    reminder: 'If this creature has no +1/+1 counters on it, put N +1/+1 counter(s) on it.',
    example: 'Incubation Druid',
    introduced: 'Ravnica Allegiance',
    scryfallQuery: 'o:adapt',
  },
  {
    keyword: 'Graft',
    type: 'mechanic',
    tier: 'returning',
    definition: 'This creature enters the battlefield with N +1/+1 counters on it. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this creature onto that creature.',
    reminder: 'This creature enters the battlefield with N +1/+1 counters on it. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this creature onto it.',
    example: 'Simic Initiate',
    introduced: 'Dissension',
    scryfallQuery: 'o:graft',
  },
  {
    keyword: 'Proliferate',
    type: 'action',
    tier: 'returning',
    definition: 'Choose any number of permanents and/or players, then give each another counter of each kind that permanent or player already has.',
    reminder: 'Choose any number of permanents and/or players, then give each another counter of each kind that permanent or player already has.',
    example: 'Evolution Sage',
    introduced: 'Scars of Mirrodin',
    scryfallQuery: 'o:proliferate',
  },

  // ── Additional Returning — Creature Combat Abilities ─────────────────
  {
    keyword: 'Ninjutsu',
    type: 'mechanic',
    tier: 'returning',
    definition: "Return an unblocked attacking creature you control to its owner's hand: Put this card from your hand onto the battlefield tapped and attacking.",
    reminder: 'Return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.',
    example: "Sakashima's Student",
    introduced: 'Betrayers of Kamigawa',
    scryfallQuery: 'o:ninjutsu',
  },
  {
    keyword: 'Crew',
    type: 'mechanic',
    tier: 'returning',
    definition: "Tap any number of creatures you control with total power N or greater: This Vehicle becomes an artifact creature until end of turn.",
    reminder: 'Tap any number of creatures you control with total power N or greater: This Vehicle becomes an artifact creature until end of turn.',
    example: "Smuggler's Copter",
    introduced: 'Kaladesh',
    scryfallQuery: 'o:crew',
  },
  {
    keyword: 'Bestow',
    type: 'mechanic',
    tier: 'returning',
    definition: "If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached to a creature.",
    reminder: "If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached to a creature.",
    example: 'Nighthowler',
    introduced: 'Theros',
    scryfallQuery: 'o:bestow',
  },
  {
    keyword: 'Dash',
    type: 'mechanic',
    tier: 'returning',
    definition: "You may cast this spell for its dash cost. If you do, it gains haste, and it's returned from the battlefield to its owner's hand at the beginning of the next end step.",
    reminder: "You may cast this spell for its dash cost. If you do, it gains haste, and it's returned from the battlefield to its owner's hand at the beginning of the next end step.",
    example: "Kolaghan, the Storm's Fury",
    introduced: 'Fate Reforged',
    scryfallQuery: 'o:dash',
  },
  {
    keyword: 'Blitz',
    type: 'mechanic',
    tier: 'returning',
    definition: 'If you cast this spell for its blitz cost, it gains haste and "when this creature dies, draw a card," and it\'s sacrificed at the beginning of the next end step.',
    reminder: "If you cast this spell for its blitz cost, it gains haste and \"when this creature dies, draw a card,\" and it's sacrificed at the beginning of the next end step.",
    example: 'Goblin Anarchomancer',
    introduced: 'Streets of New Capenna',
    scryfallQuery: 'o:blitz',
  },
  {
    keyword: 'Connive',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.',
    reminder: 'Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.',
    example: 'Wingshield Agent',
    introduced: 'Streets of New Capenna',
    scryfallQuery: 'o:connive',
  },
  {
    keyword: 'Training',
    type: 'ability',
    tier: 'returning',
    definition: 'Whenever this creature attacks with another creature with greater power, put a +1/+1 counter on this creature.',
    reminder: 'Whenever this creature attacks with another creature with greater power, put a +1/+1 counter on this creature.',
    example: 'Hopeful Initiate',
    introduced: 'Innistrad: Crimson Vow',
    scryfallQuery: 'o:training',
  },
  {
    keyword: 'Backup',
    type: 'mechanic',
    tier: 'returning',
    definition: 'When this creature enters, put N +1/+1 counters on target creature. If that target is another creature, it gains each non-backup ability this creature has until end of turn.',
    reminder: 'When this creature enters, put N +1/+1 counter(s) on target creature. If that target is another creature, it gains each non-backup ability this creature has until end of turn.',
    example: 'Backup Agent',
    introduced: 'March of the Machine',
    scryfallQuery: 'o:backup',
  },
  {
    keyword: 'Exert',
    type: 'mechanic',
    tier: 'returning',
    definition: "You may exert this creature as it attacks. When you do, it doesn't untap during your next untap step, but an additional effect occurs.",
    reminder: "You may exert this creature as it attacks. (An exerted creature won't untap during your next untap step.)",
    example: 'Glory-Bound Initiate',
    introduced: 'Amonkhet',
    scryfallQuery: 'o:exert',
  },

  // ── Additional Returning — Combat Triggers ────────────────────────────
  {
    keyword: 'Battalion',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Whenever this creature and at least two other creatures attack, a bonus effect occurs.',
    reminder: 'Whenever this creature and at least two other creatures attack, [effect].',
    example: 'Boros Elite',
    introduced: 'Gatecrash',
    scryfallQuery: 'o:battalion',
  },
  {
    keyword: 'Bloodrush',
    type: 'mechanic',
    tier: 'returning',
    definition: 'Discard this card: Target attacking creature gets a bonus until end of turn.',
    reminder: 'Discard this card: Target attacking creature gets [bonus] until end of turn.',
    example: 'Ghor-Clan Rampager',
    introduced: 'Gatecrash',
    scryfallQuery: 'o:bloodrush',
  },
  {
    keyword: 'Foray',
    type: 'mechanic',
    tier: 'returning',
    definition: 'An ability that triggers the first time you attack each turn.',
    example: 'Roving Keep',
    introduced: 'Throne of Eldraine',
    scryfallQuery: 'o:foray',
  },
  {
    keyword: 'Raid',
    type: 'mechanic',
    tier: 'returning',
    definition: 'A bonus effect that applies if you attacked with a creature this turn.',
    example: 'Mardu Heart-Piercer',
    introduced: 'Khans of Tarkir',
    scryfallQuery: 'o:raid',
  },
  {
    keyword: 'Ferocious',
    type: 'mechanic',
    tier: 'returning',
    definition: 'A bonus effect that applies if you control a creature with power 4 or greater.',
    example: "Crater's Claws",
    introduced: 'Khans of Tarkir',
    scryfallQuery: 'o:ferocious',
  },

  // ── Retired ─────────────────────────────────────────────────────────
  {
    keyword: 'Regenerate',
    type: 'action',
    tier: 'retired',
    definition: 'The next time this permanent would be destroyed this turn, instead tap it, remove it from combat, and remove all damage from it.',
    example: 'Troll Ascetic',
    introduced: 'Limited Edition Alpha',
  },
  {
    keyword: 'Banding',
    type: 'ability',
    tier: 'retired',
    definition: 'Any creatures with banding, and up to one without, can attack in a band. The attacking player assigns damage for blocked bands.',
    reminder: "Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.",
    example: 'Benalish Hero',
    introduced: 'Limited Edition Alpha',
  },
]

// Create a map for quick lookups
export const KEYWORDS_MAP = new Map<string, KeywordDefinition>(
  KEYWORDS.map((kw) => [kw.keyword.toLowerCase(), kw])
)

// Get all keywords of a specific type
export function getKeywordsByType(type: KeywordDefinition['type']): KeywordDefinition[] {
  return KEYWORDS.filter((kw) => kw.type === type)
}

// Search keywords by query
export function searchKeywords(query: string): KeywordDefinition[] {
  const lowerQuery = query.toLowerCase().trim()
  if (!lowerQuery) return KEYWORDS

  return KEYWORDS.filter(
    (kw) =>
      kw.keyword.toLowerCase().includes(lowerQuery) ||
      kw.definition.toLowerCase().includes(lowerQuery) ||
      kw.reminder?.toLowerCase().includes(lowerQuery)
  )
}
