import { TokenDefinition } from '@/types/tokens'

export const TOKENS: TokenDefinition[] = [
  // ── Creature Tokens — White ─────────────────────────────────────────
  {
    name: 'Soldier',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Soldier',
    abilities: [],
    madeBy: ['Raise the Alarm', 'Call the Conclave', 'Captain of the Watch'],
  },
  {
    name: 'Angel',
    colors: ['W'],
    type: 'creature',
    power: '4',
    toughness: '4',
    typeLine: 'Creature — Angel',
    abilities: ['Flying', 'Vigilance'],
    madeBy: ['Entreat the Angels', 'Emeria, Shattered Skyclave', 'Avacyn, Angel of Hope'],
  },
  {
    name: 'Bird',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Bird',
    abilities: ['Flying'],
    madeBy: ['Migratory Route', 'Aven Wind Guide'],
  },
  {
    name: 'Spirit (White)',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Spirit',
    abilities: ['Flying'],
    madeBy: ['Lingering Souls', 'Spectral Procession', 'Midnight Haunting'],
  },
  {
    name: 'Human (White)',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Human',
    abilities: [],
    madeBy: ['Increasing Devotion', 'Thraben Doomsayer'],
  },
  {
    name: 'Knight (White)',
    colors: ['W'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Knight',
    abilities: ['Vigilance'],
    madeBy: ['History of Benalia', 'Inspiring Commander'],
  },
  {
    name: 'Pegasus',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Pegasus',
    abilities: ['Flying'],
    madeBy: ["Oketra's Monument", 'Decree of Justice'],
  },

  // ── Creature Tokens — Blue ──────────────────────────────────────────
  {
    name: 'Drake',
    colors: ['U'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Drake',
    abilities: ['Flying'],
    madeBy: ['Talrand, Sky Summoner', 'Whirler Witch'],
  },
  {
    name: 'Merfolk (Blue)',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Merfolk',
    abilities: [],
    madeBy: ['Lullmage Mentor', 'Deepchannel Mentor', 'Stonybrook Schoolmaster'],
  },
  {
    name: 'Illusion',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Illusion',
    abilities: ['Flying'],
    madeBy: ['Meloku the Clouded Mirror', 'Vedalken Shackles'],
  },
  {
    name: 'Squid',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Squid',
    abilities: ['Islandwalk'],
    madeBy: ['Kiora, the Crashing Wave'],
  },
  {
    name: 'Thopter (Blue)',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Thopter Artifact',
    abilities: ['Flying'],
    madeBy: ['Thopter Spy Network', 'Whirler Rogue'],
  },

  // ── Creature Tokens — Black ─────────────────────────────────────────
  {
    name: 'Zombie',
    colors: ['B'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Zombie',
    abilities: [],
    madeBy: ['Army of the Damned', 'Endless Ranks of the Dead', 'Josu Vess, Lich Knight'],
  },
  {
    name: 'Vampire (Black)',
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Vampire',
    abilities: ['Flying', 'Lifelink'],
    madeBy: ["Legion's Landing", 'Call the Bloodline'],
  },
  {
    name: 'Rat',
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Rat',
    abilities: [],
    madeBy: ['Rat Colony', 'Pack Rat'],
  },
  {
    name: 'Skeleton',
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Skeleton',
    abilities: [],
    madeBy: ['Ayara, Widow of the Realm', 'Skirsdag Flayer'],
  },

  // ── Creature Tokens — Red ───────────────────────────────────────────
  {
    name: 'Goblin',
    colors: ['R'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Goblin',
    abilities: [],
    madeBy: ['Krenko, Mob Boss', 'Dragon Fodder', 'Hordeling Outburst'],
  },
  {
    name: 'Dragon',
    colors: ['R'],
    type: 'creature',
    power: '5',
    toughness: '5',
    typeLine: 'Creature — Dragon',
    abilities: ['Flying'],
    madeBy: ['Dragonmaster Outcast', 'Utvara Hellkite'],
  },
  {
    name: 'Elemental (Red)',
    colors: ['R'],
    type: 'creature',
    power: '3',
    toughness: '1',
    typeLine: 'Creature — Elemental',
    abilities: ['Trample', 'Haste'],
    madeBy: ['Omnath, Locus of Rage', 'Chandra, Torch of Defiance'],
  },
  {
    name: 'Devil',
    colors: ['R'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Devil',
    abilities: ['When this creature dies, it deals 1 damage to any target.'],
    madeBy: ['Zurzoth, Chaos Rider', 'Tibalt, Rakish Instigator'],
  },

  // ── Creature Tokens — Green ─────────────────────────────────────────
  {
    name: 'Saproling',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Saproling',
    abilities: [],
    madeBy: ['Tendershoot Dryad', 'Sprout Swarm', 'Slimefoot, the Stowaway'],
  },
  {
    name: 'Beast',
    colors: ['G'],
    type: 'creature',
    power: '3',
    toughness: '3',
    typeLine: 'Creature — Beast',
    abilities: [],
    madeBy: ['Garruk Wildspeaker', 'Rampaging Baloths', 'Call of the Herd'],
  },
  {
    name: 'Insect (Green)',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Insect',
    abilities: ['Flying', 'Deathtouch'],
    madeBy: ['Hornet Queen', 'Ishkanah, Grafwidow'],
  },
  {
    name: 'Plant',
    colors: ['G'],
    type: 'creature',
    power: '0',
    toughness: '1',
    typeLine: 'Creature — Plant',
    abilities: [],
    madeBy: ['Avenger of Zendikar', 'Vigor'],
  },
  {
    name: 'Wolf',
    colors: ['G'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Wolf',
    abilities: [],
    madeBy: ['Garruk, Primal Hunter', 'Arlinn Kord', 'Howlpack Piper'],
  },
  {
    name: 'Wurm (Green)',
    colors: ['G'],
    type: 'creature',
    power: '3',
    toughness: '3',
    typeLine: 'Creature — Wurm',
    abilities: ['Deathtouch'],
    madeBy: ['Garruk, Primal Hunter', 'Advent of the Wurm'],
  },
  {
    name: 'Spider',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '2',
    typeLine: 'Creature — Spider',
    abilities: ['Reach'],
    madeBy: ['Ishkanah, Grafwidow', 'Spider Spawning'],
  },
  {
    name: 'Squirrel',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Squirrel',
    abilities: [],
    madeBy: ['Chatterfang, Squirrel General', 'Squirrel Nest'],
  },

  // ── Creature Tokens — Multicolor ────────────────────────────────────
  {
    name: 'Faerie Rogue',
    colors: ['U', 'B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Faerie Rogue',
    abilities: ['Flying'],
    madeBy: ['Bitterblossom', 'Notorious Throng'],
  },
  {
    name: 'Elf Warrior',
    colors: ['G', 'W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Elf Warrior',
    abilities: [],
    madeBy: ['Voice of Resurgence', 'Rhys the Redeemed'],
  },
  {
    name: 'Knight (White/Black)',
    colors: ['W', 'B'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Knight',
    abilities: ['Vigilance', 'Lifelink'],
    madeBy: ['Sorin, Solemn Visitor', "Elspeth, Sun's Champion"],
  },
  {
    name: 'Human Soldier',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Human Soldier',
    abilities: [],
    madeBy: ["Elspeth, Sun's Champion", 'Secure the Wastes'],
  },
  {
    name: 'Warrior',
    colors: ['W', 'B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Warrior',
    abilities: [],
    madeBy: ['Secure the Wastes', 'Warriors of the Pale'],
  },

  // ── Creature Tokens — Colorless ─────────────────────────────────────
  {
    name: 'Construct',
    colors: ['C'],
    type: 'creature',
    power: '*',
    toughness: '*',
    typeLine: 'Creature — Construct Artifact',
    abilities: [],
    madeBy: ['Urza, Lord High Artificer', 'Thopter Foundry'],
  },
  {
    name: 'Golem',
    colors: ['C'],
    type: 'creature',
    power: '3',
    toughness: '3',
    typeLine: 'Creature — Golem Artifact',
    abilities: [],
    madeBy: ['Precursor Golem', 'Spine of Ish Sah'],
  },
  {
    name: 'Eldrazi Scion',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Eldrazi Scion',
    abilities: ['Sacrifice this creature: Add C.'],
    madeBy: ['From Beyond', 'Blight Herder', 'Incubator Drone'],
  },
  {
    name: 'Eldrazi Spawn',
    colors: ['C'],
    type: 'creature',
    power: '0',
    toughness: '1',
    typeLine: 'Creature — Eldrazi Spawn',
    abilities: ['Sacrifice this creature: Add C.'],
    madeBy: ["Kozilek's Predator", 'Nest Invader', 'Awakening Zone'],
  },
  {
    name: 'Myr',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Myr Artifact',
    abilities: [],
    madeBy: ['Myr Battlesphere', 'Myrsmith'],
  },
  {
    name: 'Servo',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Servo Artifact',
    abilities: [],
    madeBy: ['Servo Exhibition', "Sram's Expertise", 'Toolcraft Exemplar'],
  },
  {
    name: 'Thopter (Colorless)',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Thopter Artifact',
    abilities: ['Flying'],
    madeBy: ['Thopter Foundry', 'Master of Etherium', 'Padeem, Consul of Innovation'],
  },

  // ── Artifact Tokens ──────────────────────────────────────────────────
  {
    name: 'Treasure',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Treasure',
    abilities: ['Tap, Sacrifice this artifact: Add one mana of any color.'],
    madeBy: ['Smothering Tithe', 'Xorn', 'Prosper, Tome-Bound'],
  },
  {
    name: 'Clue',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Clue',
    abilities: ['2, Sacrifice this artifact: Draw a card.'],
    madeBy: ['Thraben Inspector', 'Graf Mole', "Tamiyo's Journal"],
  },
  {
    name: 'Food',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Food',
    abilities: ['2, Tap, Sacrifice this artifact: You gain 3 life.'],
    madeBy: ['Gilded Goose', 'The Cauldron of Eternity', 'Oko, Thief of Crowns'],
  },
  {
    name: 'Blood',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Blood',
    abilities: ['1, Tap, Discard a card, Sacrifice this artifact: Draw a card.'],
    madeBy: ['Bloodtithe Harvester', 'Voldaren Bloodcaster', "Olivia's Attendants"],
  },
  {
    name: 'Map',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Map',
    abilities: ['1, Tap, Sacrifice this artifact: Target creature you control explores.'],
    madeBy: ["Abuelo's Awakening", 'Caparocti Sunborn', 'Oltec Cloud Guard'],
  },
  {
    name: 'Gold',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Gold',
    abilities: ['Sacrifice this artifact: Add one mana of any color.'],
    madeBy: ['Revel in Riches', 'Tempt with Immortality'],
  },
  {
    name: 'Powerstone',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Powerstone',
    abilities: ["Tap: Add C. This mana can't be spent to cast nonartifact spells."],
    madeBy: ['Teferi, Temporal Pilgrim', 'Karn, Living Legacy'],
  },
  {
    name: 'Junk',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Junk',
    abilities: ['Sacrifice this artifact: Add one mana of any color. Spend this mana only to cast a spell with Casualty, Blitz, or for an activated ability.'],
    madeBy: ['Ob Nixilis, the Adversary', 'Riveteers Charm'],
  },

  // ── Emblems ──────────────────────────────────────────────────────────
  {
    name: 'Teferi Emblem',
    colors: ['C'],
    type: 'emblem',
    typeLine: 'Emblem — Teferi',
    abilities: ["You may activate loyalty abilities of planeswalkers you control on any player's turn any time you could cast an instant."],
    madeBy: ['Teferi, Hero of Dominaria'],
  },
  {
    name: 'Garruk Emblem',
    colors: ['C'],
    type: 'emblem',
    typeLine: 'Emblem — Garruk',
    abilities: ['Creatures you control get +3/+3 and have trample.'],
    madeBy: ['Garruk, Apex Predator'],
  },
  {
    name: 'Liliana Emblem',
    colors: ['C'],
    type: 'emblem',
    typeLine: 'Emblem — Liliana',
    abilities: ['At the beginning of your end step, each opponent sacrifices a creature.'],
    madeBy: ['Liliana, the Last Hope', 'Liliana Vess'],
  },
  {
    name: 'Elspeth Emblem',
    colors: ['C'],
    type: 'emblem',
    typeLine: 'Emblem — Elspeth',
    abilities: ['Creatures you control get +2/+2 and have flying.'],
    madeBy: ['Elspeth, Knight-Errant'],
  },
  {
    name: 'Chandra Emblem',
    colors: ['C'],
    type: 'emblem',
    typeLine: 'Emblem — Chandra',
    abilities: ['Whenever you cast a red spell, this emblem deals 10 damage to any target.'],
    madeBy: ['Chandra, Torch of Defiance'],
  },

  // ── Special & Commander Staples ──────────────────────────────────────
  {
    name: 'Copy',
    colors: ['C'],
    type: 'creature',
    power: '*',
    toughness: '*',
    typeLine: 'Creature — (copy of target)',
    abilities: ['This token is a copy of the chosen creature (no token type of its own).'],
    madeBy: ['Delina, Wild Mage', 'Mimic Vat', 'Orthion, Hero of Lavabrink'],
  },
  {
    name: 'Zombie Knight',
    colors: ['B'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Zombie Knight',
    abilities: ['Menace'],
    madeBy: ['Josu Vess, Lich Knight (kicked)'],
  },
  {
    name: 'Vampire (Red/White)',
    colors: ['W', 'R'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Vampire',
    abilities: ['Flying', 'First Strike', 'Haste'],
    madeBy: ['Olivia, Crimson Bride'],
  },
  {
    name: 'Zombie (Embalm)',
    colors: ['W'],
    type: 'creature',
    power: '*',
    toughness: '*',
    typeLine: 'Creature — Zombie (creature type of original card)',
    abilities: ['White Zombie token copy of the original; created via Embalm.'],
    madeBy: ['Vizier of Many Faces', 'Sacred Cat', 'Anointer Priest'],
  },
]

// Quick lookup map
export const TOKENS_MAP = new Map<string, TokenDefinition>(
  TOKENS.map((t) => [t.name.toLowerCase(), t])
)

export function searchTokens(query: string): TokenDefinition[] {
  const q = query.toLowerCase().trim()
  if (!q) return TOKENS
  return TOKENS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.typeLine.toLowerCase().includes(q) ||
      t.madeBy.some((m) => m.toLowerCase().includes(q)) ||
      t.abilities.some((a) => a.toLowerCase().includes(q))
  )
}
