import { TokenDefinition } from '@/types/tokens'

export const TOKENS: TokenDefinition[] = [
  // ── Creature Tokens — White ─────────────────────────────────────────
  {
    name: 'Soldier',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Soldier',
    abilities: [],
    madeBy: ['Raise the Alarm', 'Captain of the Watch'],
  },
  {
    name: 'Angel',
    colors: ['W'],
    type: 'creature',
    power: '4',
    toughness: '4',
    typeLine: 'Creature — Angel',
    abilities: ["Flying"],
    madeBy: ["Entreat the Angels"],
  },
  {
    name: 'Bird',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Bird',
    abilities: ['Flying'],
    madeBy: ['Migratory Route', 'Battle Screech'],
  },
  {
    name: 'Spirit (White)',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Spirit',
    abilities: ['Flying'],
    madeBy: ['Lingering Souls', 'Spectral Procession', 'Midnight Haunting'],
  },
  {
    name: 'Human (White)',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Human',
    abilities: [],
    madeBy: ["Increasing Devotion", "Thraben Doomsayer", "Gather the Townsfolk"],
  },
  {
    name: 'Knight (White)',
    colors: ['W'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Knight',
    abilities: ['Vigilance'],
    madeBy: ['History of Benalia'],
  },
  {
    name: 'Pegasus',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Pegasus',
    abilities: ['Flying'],
    madeBy: ['Sacred Mesa'],
  },

  // ── Creature Tokens — Blue ──────────────────────────────────────────
  {
    name: 'Drake',
    colors: ['U'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Drake',
    abilities: ['Flying'],
    madeBy: ['Talrand, Sky Summoner'],
  },
  {
    name: 'Merfolk (Blue)',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Merfolk',
    abilities: [],
    madeBy: ["Lullmage Mentor"],
  },
  {
    name: 'Illusion',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Illusion',
    abilities: ['Flying'],
    madeBy: ['Meloku the Clouded Mirror'],
  },
  {
    name: 'Thopter (Blue)',
    colors: ['U'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Artifact Creature — Thopter',
    abilities: ['Flying'],
    madeBy: ["Thopter Foundry"],
  },

  // ── Creature Tokens — Black ─────────────────────────────────────────
  {
    name: 'Zombie',
    colors: ['B'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Zombie',
    abilities: [],
    madeBy: ["Army of the Damned", "Endless Ranks of the Dead"],
  },
  {
    name: "Vampire Knight",
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: "Creature — Vampire Knight",
    abilities: ["Lifelink"],
    madeBy: ["Call the Bloodline"],
  },
  {
    name: 'Rat',
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Rat',
    abilities: [],
    madeBy: ["Chittering Witch"],
  },
  {
    name: 'Skeleton',
    colors: ['B'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Skeleton',
    abilities: ["B: Regenerate this creature."],
    madeBy: ["Skeletonize"],
  },

  // ── Creature Tokens — Red ───────────────────────────────────────────
  {
    name: 'Goblin',
    colors: ['R'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Goblin',
    abilities: [],
    madeBy: ['Krenko, Mob Boss', 'Dragon Fodder', 'Hordeling Outburst'],
  },
  {
    name: 'Dragon',
    colors: ['R'],
    type: 'creature',
    power: '5',
    toughness: '5',
    typeLine: 'Creature — Dragon',
    abilities: ['Flying'],
    madeBy: ["Dragonmaster Outcast"],
  },
  {
    name: "Spark Elemental",
    colors: ['R'],
    type: 'creature',
    power: '3',
    toughness: '1',
    typeLine: 'Creature — Elemental',
    abilities: ["Trample", "Haste", "At the beginning of the end step, sacrifice this creature."],
    madeBy: ["Sparkspitter"],
  },
  {
    name: 'Devil',
    colors: ['R'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Devil',
    abilities: ['When this creature dies, it deals 1 damage to any target.'],
    madeBy: ['Zurzoth, Chaos Rider', 'Tibalt, Rakish Instigator'],
  },

  // ── Creature Tokens — Green ─────────────────────────────────────────
  {
    name: 'Saproling',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Saproling',
    abilities: [],
    madeBy: ['Tendershoot Dryad', 'Sprout Swarm', 'Slimefoot, the Stowaway'],
  },
  {
    name: 'Beast',
    colors: ['G'],
    type: 'creature',
    power: '3',
    toughness: '3',
    typeLine: 'Creature — Beast',
    abilities: [],
    madeBy: ['Garruk Wildspeaker', 'Garruk, Primal Hunter'],
  },
  {
    name: 'Insect (Green)',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Insect',
    abilities: ['Flying', 'Deathtouch'],
    madeBy: ['Hornet Queen'],
  },
  {
    name: 'Plant',
    colors: ['G'],
    type: 'creature',
    power: '0',
    toughness: '1',
    typeLine: 'Creature — Plant',
    abilities: [],
    madeBy: ['Avenger of Zendikar', 'Nissa, Voice of Zendikar'],
  },
  {
    name: 'Wolf',
    colors: ['G'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Wolf',
    abilities: [],
    madeBy: ["Arlinn Kord"],
  },
  {
    name: 'Wurm',
    colors: ['G'],
    type: 'creature',
    power: '6',
    toughness: '6',
    typeLine: 'Creature — Wurm',
    abilities: [],
    madeBy: ['Garruk, Primal Hunter'],
  },
  {
    name: 'Spider',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '2',
    typeLine: 'Creature — Spider',
    abilities: ['Reach'],
    madeBy: ['Ishkanah, Grafwidow', 'Spider Spawning'],
  },
  {
    name: 'Squirrel',
    colors: ['G'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Squirrel',
    abilities: [],
    madeBy: ['Chatterfang, Squirrel General', 'Squirrel Nest'],
  },

  // ── Creature Tokens — Multicolor ────────────────────────────────────
  {
    name: 'Faerie Rogue',
    colors: ["B"],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Faerie Rogue',
    abilities: ['Flying'],
    madeBy: ['Bitterblossom', 'Notorious Throng'],
  },
  {
    name: 'Elf Warrior',
    colors: ['G', 'W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Elf Warrior',
    abilities: [],
    madeBy: ["Rhys the Redeemed"],
  },
  {
    name: 'Human Soldier',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Human Soldier',
    abilities: [],
    madeBy: ["Elspeth, Sun's Nemesis"],
  },
  {
    name: 'Warrior',
    colors: ['W'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Warrior',
    abilities: [],
    madeBy: ['Secure the Wastes', 'Mardu Hordechief'],
  },

  // ── Creature Tokens — Colorless ─────────────────────────────────────
  {
    name: 'Construct',
    colors: ['C'],
    type: 'creature',
    power: "0",
    toughness: "0",
    typeLine: 'Artifact Creature — Construct',
    abilities: ["This creature gets +1/+1 for each artifact you control."],
    madeBy: ["Urza, Lord High Artificer"],
  },
  {
    name: 'Golem',
    colors: ['C'],
    type: 'creature',
    power: '3',
    toughness: '3',
    typeLine: 'Artifact Creature — Golem',
    abilities: [],
    madeBy: ["Precursor Golem"],
  },
  {
    name: 'Eldrazi Scion',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Creature — Eldrazi Scion',
    abilities: ['Sacrifice this creature: Add C.'],
    madeBy: ['From Beyond', 'Blight Herder', 'Incubator Drone'],
  },
  {
    name: 'Eldrazi Spawn',
    colors: ['C'],
    type: 'creature',
    power: '0',
    toughness: '1',
    typeLine: 'Creature — Eldrazi Spawn',
    abilities: ['Sacrifice this creature: Add C.'],
    madeBy: ["Kozilek's Predator", 'Nest Invader', 'Awakening Zone'],
  },
  {
    name: 'Myr',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Artifact Creature — Myr',
    abilities: [],
    madeBy: ['Myr Battlesphere', 'Myrsmith'],
  },
  {
    name: 'Servo',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Artifact Creature — Servo',
    abilities: [],
    madeBy: ['Servo Exhibition', "Sram's Expertise"],
  },
  {
    name: 'Thopter (Colorless)',
    colors: ['C'],
    type: 'creature',
    power: '1',
    toughness: '1',
    typeLine: 'Artifact Creature — Thopter',
    abilities: ['Flying'],
    madeBy: ["Sai, Master Thopterist", "Thopter Spy Network", "Whirler Rogue"],
  },

  // ── Artifact Tokens ──────────────────────────────────────────────────
  {
    name: 'Treasure',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Treasure',
    abilities: ['Tap, Sacrifice this artifact: Add one mana of any color.'],
    madeBy: ["Smothering Tithe", "Prosper, Tome-Bound"],
  },
  {
    name: 'Clue',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Clue',
    abilities: ['2, Sacrifice this artifact: Draw a card.'],
    madeBy: ['Thraben Inspector', "Tamiyo's Journal"],
  },
  {
    name: 'Food',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Food',
    abilities: ['2, Tap, Sacrifice this artifact: You gain 3 life.'],
    madeBy: ["Gilded Goose", "Oko, Thief of Crowns"],
  },
  {
    name: 'Blood',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Blood',
    abilities: ['1, Tap, Discard a card, Sacrifice this artifact: Draw a card.'],
    madeBy: ['Bloodtithe Harvester', 'Voldaren Bloodcaster', "Olivia's Attendants"],
  },
  {
    name: 'Map',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Map',
    abilities: ["1, Tap, Sacrifice this artifact: Target creature you control explores. Activate only as a sorcery."],
    madeBy: ["Restless Anchorage"],
  },
  {
    name: 'Powerstone',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Powerstone',
    abilities: ["Tap: Add C. This mana can't be spent to cast nonartifact spells."],
    madeBy: ["Karn, Living Legacy"],
  },
  {
    name: 'Junk',
    colors: ['C'],
    type: 'artifact',
    typeLine: 'Artifact — Junk',
    abilities: ["Tap, Sacrifice this artifact: Exile the top card of your library. You may play that card this turn. Activate only as a sorcery."],
    madeBy: ["Dogmeat, Ever Loyal"],
  },

  // ── Emblems ──────────────────────────────────────────────────────────
  {
    name: 'Teferi Emblem',
    colors: [],
    type: 'emblem',
    typeLine: 'Emblem — Teferi',
    abilities: ["You may activate loyalty abilities of planeswalkers you control on any player's turn any time you could cast an instant."],
    madeBy: ["Teferi, Temporal Archmage"],
  },
  {
    name: 'Garruk Emblem',
    colors: [],
    type: 'emblem',
    typeLine: 'Emblem — Garruk',
    abilities: ['Creatures you control get +3/+3 and have trample.'],
    madeBy: ["Garruk, Cursed Huntsman"],
  },
  {
    name: 'Liliana Emblem',
    colors: [],
    type: 'emblem',
    typeLine: 'Emblem — Liliana',
    abilities: ["At the beginning of your end step, create X 2/2 black Zombie creature tokens, where X is two plus the number of Zombies you control."],
    madeBy: ["Liliana, the Last Hope"],
  },
  {
    name: 'Elspeth Emblem',
    colors: [],
    type: 'emblem',
    typeLine: 'Emblem — Elspeth',
    abilities: ['Creatures you control get +2/+2 and have flying.'],
    madeBy: ["Elspeth, Sun's Champion"],
  },
  {
    name: 'Chandra Emblem',
    colors: [],
    type: 'emblem',
    typeLine: 'Emblem — Chandra',
    abilities: ["Whenever you cast a spell, this emblem deals 5 damage to any target."],
    madeBy: ['Chandra, Torch of Defiance'],
  },

  // ── Special & Commander Staples ──────────────────────────────────────
  {
    name: 'Copy',
    colors: [],
    type: 'creature',
    typeLine: "Creature copy — characteristics vary",
    abilities: ["Use the copied creature’s characteristics, with any exceptions specified by the effect creating this token."],
    madeBy: ['Delina, Wild Mage', 'Mimic Vat', 'Orthion, Hero of Lavabrink'],
  },
  {
    name: 'Zombie Knight',
    colors: ['B'],
    type: 'creature',
    power: '2',
    toughness: '2',
    typeLine: 'Creature — Zombie Knight',
    abilities: ['Menace'],
    madeBy: ["Josu Vess, Lich Knight"],
  },
  {
    name: 'Zombie (Embalm)',
    colors: ['W'],
    type: 'creature',
    power: '*',
    toughness: '*',
    typeLine: 'Creature — Zombie (creature type of original card)',
    abilities: ["Copy of the original creature, except white, with no mana cost, and Zombie in addition to its other creature types."],
    madeBy: ['Vizier of Many Faces', 'Sacred Cat', 'Anointer Priest'],
  },
]

// Quick lookup map
export const TOKENS_MAP = new Map<string, TokenDefinition>(
  TOKENS.map((t) => [t.name.toLowerCase(), t])
)

export function searchTokens(query: string): TokenDefinition[] {
  const q = query.toLowerCase().trim()
  if (!q) return TOKENS
  return TOKENS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.typeLine.toLowerCase().includes(q) ||
      t.madeBy.some((m) => m.toLowerCase().includes(q)) ||
      t.abilities.some((a) => a.toLowerCase().includes(q))
  )
}
